name: Greetings

on: [pull_request, issues, push]

jobs:
    greeting:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - uses: actions/first-interaction@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  issue-message: 'Thank you for your first contribution!'
                  pr-message: 'Thank you for your first pull request! Your code will be reviewed shortly!'
                  push: 'Thank you for your first push! Please review the code and submit a pull request.'
