name: Build
on:
    pull_request:
        branches: [trunk]
        paths:
            - '**.ts'
            - '**.yml'
            - '**.yaml'
            - 'Dockerfile'
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
                os: [linux]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci --no-optional --quiet
            - run: npm run lint:fix
            - run: npm run build
            - run: npm test
