name: Deploy
on:
    push:
        branches: [trunk]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
                os: [linux]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci --no-optional --quiet
            - run: npm run lint:fix
            - run: npm run build
            - run: npm test
    deploy:
        name: Setup Gcloud Account
        if: github.event.pull_request.closed == 'true'
        runs-on: ubuntu-latest
        environment:
            name: Production Release
            url: https://view-counter.tobyhagan.com
        needs:
            - build
        env:
            IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:
            - name: Login
              uses: google-github-actions/setup-gcloud@v0
              with:
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
                  service_account_email: ${{ secrets.GCP_EMAIL }}
                  service_account_key: ${{ secrets.GCP_CREDENTIALS }}

            - name: Configure Docker
              run: gcloud auth configure-docker --quiet

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Build Docker image
              run: docker build . -t $IMAGE_NAME

            - name: Push Docker image
              run: docker push $IMAGE_NAME

            - name: Deploy Docker image
              run: gcloud run deploy ${{ secrets.GCP_APP_NAME}} --image $IMAGE_NAME --region us-central1 --platform managed
