name: Deploy
on:
    push:
        branches: [trunk]
    pull_request:
        branches: [trunk]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
                cache-restore: [true, false]
                os: [linux, windows, macos]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci --no-optional --quiet
            - run: npm run lint:fix
            - run: npm run build
            - run: npm test
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: Production
            url: https://view-counter.tobyhagan.com
        strategy:
            matrix:
                node-version: [16.x]
                cache-restore: [true, false]
                os: [linux, windows, macos]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: 'npm'
            - run: npm ci --no-optional --quiet
            - run: npm run lint:fix
            - run: npm run build
            - run: npm test
            - run: npm run deploy
            - name: Deploy to GCR
              uses: gcr-deploy@v1
              with:
                  image: gcr.io/${secrets.GOOGLE_PROJECT_ID}/${github.event.repository.name}
                  tag: ${{ secrets.GCR_TAG }}
                  cache-restore: ${{ matrix.cache-restore }}
                  os: ${{ matrix.os }}
